
CREATE TABLE  CE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    services VARCHAR(15) NOT NULL,
    address VARCHAR(15) NOT NULL
);


